import "./modal-ui-choice.js";
import "./modal-import.js";
import "./modal-study-string.js";
import "./modal-load-game.js";
import "./modal-std-store.js";
import "./modal-h2p.js";
import "./modal-progress-bar.js";
import "./modal-away-progress.js";
import "./modal-sacrifice.js";
import "./modal-break-infinity.js";
import "./modal-automator-script-delete.js";
import "./modal-automator-script-import.js";
import "./modal-set-save-delete.js";
import "./modal-glyph-undo.js";
import "./modal-glyph-replace.js";
import "./modal-glyph-showcase-panel.js";

import "../celestials/subtabs/ra/reality-glyph-creation.js";
import "../celestials/subtabs/laitela/singularity-milestones-modal.js";
