
const PERKS = {
  GLYPH_CHOOSE3: 0,
  START_AM1: 10,
  START_AM2: 11,
  START_IP1: 12,
  START_IP2: 13,
  START_EP1: 14,
  START_EP2: 15,
  START_EP3: 16,
  START_TP: 17,
  GLYPH_LEVEL_INC1: 20,
  GLYPH_LEVEL_INC2: 21,
  GLYPH_CHOOSE4: 22,
  GLYPH_RARITY_INC: 23,
  AUTOMATION_ROW_INC1: 30,
  AUTOMATION_ROW_INC2: 31,
  AUTOMATION_ROW_SCALING: 32,
  AUTOUNLOCK_EU1: 40,
  AUTOUNLOCK_EU2: 41,
  AUTOUNLOCK_DILATION1: 42,
  AUTOUNLOCK_DILATION2: 43,
  AUTOUNLOCK_DILATION3: 44,
  AUTOUNLOCK_TD: 45,
  AUTOUNLOCK_REALITY: 46,
  BYPASS_ID_AM: 51,
  BYPASS_DG_RESET: 52,
  BYPASS_EC_DILATION: 53,
  BYPASS_EC1_LOCK: 54,
  BYPASS_EC2_LOCK: 55,
  BYPASS_EC3_LOCK: 56,
  BYPASS_EC5_LOCK: 57,
  AUTOCOMPLETE_EC1: 60,
  AUTOCOMPLETE_EC2: 61,
  AUTOCOMPLETE_EC3: 62,
  AUTOCOMPLETE_EC4: 63,
  AUTOCOMPLETE_EC5: 64,
  TS_ACTIVE_EP: 70,
  TS_IDLE_EP: 71,
  TS_EC_REQ: 72,
  TS_EC_BULK: 73,
  RETROACTIVE_TP1: 80,
  RETROACTIVE_TP2: 81,
  RETROACTIVE_TP3: 82,
  RETROACTIVE_TP4: 83,
  AUTOBUYER_DILATION: 100,
  AUTOBUYER_FASTER_ID: 101,
  AUTOBUYER_FASTER_REPLICANTI: 102,
  AUTOBUYER_FASTER_DILATION: 103,
  AUTOBUYER_TT1: 104,
  AUTOBUYER_TT2: 105,
  AUTOBUYER_TT3: 106,
  AUTOBUYER_TT4: 107,
  ACHIEVEMENT_ROW1: 201,
  ACHIEVEMENT_ROW2: 202,
  ACHIEVEMENT_ROW3: 203,
  ACHIEVEMENT_ROW4: 204,
  ACHIEVEMENT_ROW5: 205,
  ACHIEVEMENT_ROW6: 206,
  ACHIEVEMENT_ROW7: 207,
  ACHIEVEMENT_ROW8: 208,
  ACHIEVEMENT_ROW9: 209,
  ACHIEVEMENT_ROW10: 210,
  ACHIEVEMENT_ROW11: 211,
  ACHIEVEMENT_ROW12: 212,
  ACHIEVEMENT_ROW13: 213
} 

CONNECTED_PERKS = {}
function constructEdgeList() {
  CONNECTED_PERKS[PERKS.GLYPH_CHOOSE3] =  [PERKS.ACHIEVEMENT_ROW1, PERKS.START_AM1, PERKS.GLYPH_LEVEL_INC1, PERKS.GLYPH_LEVEL_INC2, PERKS.AUTOMATION_ROW_INC1, PERKS.AUTOUNLOCK_EU1, PERKS.BYPASS_EC5_LOCK];
  CONNECTED_PERKS[PERKS.START_AM1] = [PERKS.START_AM2, PERKS.START_IP1];
  CONNECTED_PERKS[PERKS.START_AM2] = [];
  CONNECTED_PERKS[PERKS.START_IP1] = [PERKS.START_IP2, PERKS.START_EP1];
  CONNECTED_PERKS[PERKS.START_IP2] = [PERKS.BYPASS_ID_AM];
  CONNECTED_PERKS[PERKS.START_EP1] = [PERKS.START_EP2, PERKS.START_TP];
  CONNECTED_PERKS[PERKS.START_EP2] = [PERKS.START_EP3];
  CONNECTED_PERKS[PERKS.START_EP3] = [];
  CONNECTED_PERKS[PERKS.START_TP] = [PERKS.RETROACTIVE_TP1];
  CONNECTED_PERKS[PERKS.GLYPH_LEVEL_INC1] = [PERKS.GLYPH_CHOOSE4];
  CONNECTED_PERKS[PERKS.GLYPH_LEVEL_INC2] = [PERKS.GLYPH_RARITY_INC];
  CONNECTED_PERKS[PERKS.GLYPH_CHOOSE4] = [PERKS.GLYPH_LEVEL_INC1, PERKS.GLYPH_RARITY_INC];
  CONNECTED_PERKS[PERKS.GLYPH_RARITY_INC] = [PERKS.GLYPH_LEVEL_INC2, PERKS.GLYPH_CHOOSE4];
  CONNECTED_PERKS[PERKS.AUTOMATION_ROW_INC1] = [PERKS.AUTOMATION_ROW_INC2, PERKS.AUTOBUYER_FASTER_ID];
  CONNECTED_PERKS[PERKS.AUTOMATION_ROW_INC2] = [PERKS.AUTOMATION_ROW_SCALING];
  CONNECTED_PERKS[PERKS.AUTOMATION_ROW_SCALING] = [];
  CONNECTED_PERKS[PERKS.AUTOUNLOCK_EU1] = [PERKS.AUTOUNLOCK_EU2];
  CONNECTED_PERKS[PERKS.AUTOUNLOCK_EU2] = [PERKS.AUTOUNLOCK_EU1, PERKS.AUTOBUYER_DILATION];
  CONNECTED_PERKS[PERKS.AUTOUNLOCK_DILATION1] = [PERKS.AUTOUNLOCK_DILATION2];
  CONNECTED_PERKS[PERKS.AUTOUNLOCK_DILATION2] = [PERKS.AUTOUNLOCK_DILATION3];
  CONNECTED_PERKS[PERKS.AUTOUNLOCK_DILATION3] = [PERKS.AUTOBUYER_FASTER_DILATION, PERKS.AUTOUNLOCK_TD];
  CONNECTED_PERKS[PERKS.AUTOUNLOCK_TD] = [PERKS.AUTOUNLOCK_REALITY];
  CONNECTED_PERKS[PERKS.AUTOUNLOCK_REALITY] = [];
  CONNECTED_PERKS[PERKS.BYPASS_ID_AM] = [];
  CONNECTED_PERKS[PERKS.BYPASS_DG_RESET] = [PERKS.AUTOBUYER_DILATION, PERKS.RETROACTIVE_TP1];
  CONNECTED_PERKS[PERKS.BYPASS_EC_DILATION] = [];
  CONNECTED_PERKS[PERKS.BYPASS_EC1_LOCK] = [PERKS.BYPASS_EC2_LOCK, PERKS.BYPASS_EC3_LOCK, PERKS.AUTOCOMPLETE_EC1];
  CONNECTED_PERKS[PERKS.BYPASS_EC2_LOCK] = [PERKS.TS_ACTIVE_EP, PERKS.BYPASS_EC1_LOCK];
  CONNECTED_PERKS[PERKS.BYPASS_EC3_LOCK] = [PERKS.TS_IDLE_EP, PERKS.BYPASS_EC1_LOCK];
  CONNECTED_PERKS[PERKS.BYPASS_EC5_LOCK] = [PERKS.TS_ACTIVE_EP, PERKS.TS_IDLE_EP];
  CONNECTED_PERKS[PERKS.AUTOCOMPLETE_EC1] = [PERKS.AUTOCOMPLETE_EC2];
  CONNECTED_PERKS[PERKS.AUTOCOMPLETE_EC2] = [PERKS.AUTOCOMPLETE_EC3];
  CONNECTED_PERKS[PERKS.AUTOCOMPLETE_EC3] = [PERKS.AUTOCOMPLETE_EC4];
  CONNECTED_PERKS[PERKS.AUTOCOMPLETE_EC4] = [PERKS.AUTOCOMPLETE_EC5];
  CONNECTED_PERKS[PERKS.AUTOCOMPLETE_EC5] = [];
  CONNECTED_PERKS[PERKS.TS_ACTIVE_EP] = [PERKS.BYPASS_EC2_LOCK, PERKS.TS_EC_REQ];
  CONNECTED_PERKS[PERKS.TS_IDLE_EP] = [PERKS.BYPASS_EC3_LOCK, PERKS.AUTOBUYER_TT1];
  CONNECTED_PERKS[PERKS.TS_EC_REQ] = [PERKS.TS_EC_BULK];
  CONNECTED_PERKS[PERKS.TS_EC_BULK] = [];
  CONNECTED_PERKS[PERKS.RETROACTIVE_TP1] = [PERKS.BYPASS_DG_RESET, PERKS.START_TP, PERKS.RETROACTIVE_TP2];
  CONNECTED_PERKS[PERKS.RETROACTIVE_TP2] = [PERKS.RETROACTIVE_TP3];
  CONNECTED_PERKS[PERKS.RETROACTIVE_TP3] = [PERKS.RETROACTIVE_TP4];
  CONNECTED_PERKS[PERKS.RETROACTIVE_TP4] = [];
  CONNECTED_PERKS[PERKS.AUTOBUYER_DILATION] = [PERKS.AUTOUNLOCK_EU2, PERKS.AUTOUNLOCK_DILATION1, PERKS.BYPASS_EC_DILATION, PERKS.BYPASS_DG_RESET];
  CONNECTED_PERKS[PERKS.AUTOBUYER_FASTER_ID] = [PERKS.AUTOBUYER_FASTER_REPLICANTI];
  CONNECTED_PERKS[PERKS.AUTOBUYER_FASTER_REPLICANTI] = [];
  CONNECTED_PERKS[PERKS.AUTOBUYER_FASTER_DILATION] = [];
  CONNECTED_PERKS[PERKS.AUTOBUYER_TT1] = [PERKS.AUTOBUYER_TT2];
  CONNECTED_PERKS[PERKS.AUTOBUYER_TT2] = [PERKS.AUTOBUYER_TT3];
  CONNECTED_PERKS[PERKS.AUTOBUYER_TT3] = [PERKS.AUTOBUYER_TT4];
  CONNECTED_PERKS[PERKS.AUTOBUYER_TT4] = [];
  CONNECTED_PERKS[PERKS.ACHIEVEMENT_ROW1] = [PERKS.ACHIEVEMENT_ROW2];
  CONNECTED_PERKS[PERKS.ACHIEVEMENT_ROW2] = [PERKS.ACHIEVEMENT_ROW3];
  CONNECTED_PERKS[PERKS.ACHIEVEMENT_ROW3] = [PERKS.ACHIEVEMENT_ROW4];
  CONNECTED_PERKS[PERKS.ACHIEVEMENT_ROW4] = [PERKS.ACHIEVEMENT_ROW5];
  CONNECTED_PERKS[PERKS.ACHIEVEMENT_ROW5] = [PERKS.ACHIEVEMENT_ROW6];
  CONNECTED_PERKS[PERKS.ACHIEVEMENT_ROW6] = [PERKS.ACHIEVEMENT_ROW7];
  CONNECTED_PERKS[PERKS.ACHIEVEMENT_ROW7] = [PERKS.ACHIEVEMENT_ROW8];
  CONNECTED_PERKS[PERKS.ACHIEVEMENT_ROW8] = [PERKS.ACHIEVEMENT_ROW9];
  CONNECTED_PERKS[PERKS.ACHIEVEMENT_ROW9] = [PERKS.ACHIEVEMENT_ROW10];
  CONNECTED_PERKS[PERKS.ACHIEVEMENT_ROW10] = [PERKS.ACHIEVEMENT_ROW11];
  CONNECTED_PERKS[PERKS.ACHIEVEMENT_ROW11] = [PERKS.ACHIEVEMENT_ROW12];
  CONNECTED_PERKS[PERKS.ACHIEVEMENT_ROW12] = [PERKS.ACHIEVEMENT_ROW13];
  CONNECTED_PERKS[PERKS.ACHIEVEMENT_ROW13] = [];
}
constructEdgeList();

// Reset perks if the current list is invalid, notify player too (should automatically "fix" older saves)
function checkForValidPerkList() {
  let perkIterator = player.reality.perks.values();
  let isDone = false;
  let isValid = true;
  while (!isDone) {
    let nextPerk = perkIterator.next();
    isDone = nextPerk.done;
    isValid = isDone ? isValid : isValid && (CONNECTED_PERKS[nextPerk.value] !== undefined);
  }
  if (!isValid) {
    resetPerks();
    Modal.message.show("Your old Reality perks were invalid, your perks have been reset and your perk points refunded.");
  }
}

function resetPerks() {
  player.reality.pp += player.reality.perks.length;
  player.reality.perks = [];
}

BUYABLE_PERKS = [];
function getBuyablePerks() {
  if (player.reality.perks.length == 0) {
    return [0];
  }
  let buyablePerks = [];
  for (perk in player.reality.perks) {
    if (player.reality.perks.hasOwnProperty(perk)) {
      let adjacentPerks = CONNECTED_PERKS[player.reality.perks[perk]];
      for (adjPerk in adjacentPerks) {
        let perkNum = adjacentPerks[adjPerk];
        if (adjacentPerks.hasOwnProperty(adjPerk) && !player.reality.perks.includes(perkNum) && !buyablePerks.includes(perkNum)) {
          buyablePerks.push(perkNum);
        }
      }
    }
  }
  return buyablePerks;
}
BUYABLE_PERKS = getBuyablePerks();

function canBuyPerk(id, cost) {
  return player.reality.pp >= cost && BUYABLE_PERKS.includes(id)
}

function buyPerk(id, cost) {
  if (!canBuyPerk(id, cost)) return false
  player.reality.perks.push(id);
  Perks.updateAchSkipCount();
  updateAutomatorRows();
  player.reality.pp -= cost
  BUYABLE_PERKS = getBuyablePerks();
  document.getElementById("pp").textContent = "You have " + player.reality.pp + " Perk Point" + ((player.reality.pp === 1) ? "." : "s.")
  if (player.reality.perks.length == Object.keys(CONNECTED_PERKS).length) giveAchievement("Perks of living")
}

class PerkState {
  constructor(config) {
    this._id = config.id;
    this._effect = config.effect;
  }

  get isBought() {
    return player.reality.perks.includes(this._id);
  }

  get effectValue() {
    return this._effect();
  }

  applyEffect(applyFn) {
    if (this.isBought) {
      applyFn(this.effectValue);
    }
  }
}

PerkState.allPerks = mapGameData(
  GameDatabase.reality.perks,
  config => new PerkState(config)
);

/**
 * @param {number} id
 * @returns {PerkState}
 */
function Perk(id) {
  return PerkState.allPerks[id];
}

class Perks {
  static updateAchSkipCount() {
    Perks.achSkipCount = player.reality.perks
      .filter(perk => Perks.isAchSkipPerk(perk))
      .length;
  }

  static isAchSkipPerk(id) {
    return id >= 201 && id <= 213;
  }
}

Perks.achSkipCount = 0;